# all:
# 	g++ -Iinc -Llib main.cpp -lmingw32 -lSDL2main -lSDL2 -o mygame.exe
# makefile for image , ttf ,
# all:
# 	g++ -Iinc -Llib main.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -o mygame.exe
# 
# 
# makefile for : image, ttf, musice (lasted)
all:
	g++ -Iinc -Llib main.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -o mygame.exe
